src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_inscription = null;

    #[ORM\Column(length: 30)]
    private ?string $nom = null;

    #[ORM\Column(length: 100)]
    private ?string $prenom = null;

    /**
     * @var Collection<int, Fichier>
     */
    #[ORM\OneToMany(targetEntity: Fichier::class, mappedBy: 'user')]
    private Collection $fichiers;

    public function __construct()
    {
        $this->fichiers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';
        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getDateInscription(): ?\DateTimeInterface
    {
        return $this->date_inscription;
    }

    public function setDateInscription(\DateTimeInterface $date_inscription): static
    {
        $this->date_inscription = $date_inscription;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * @return Collection<int, Fichier>
     */
    public function getFichiers(): Collection
    {
        return $this->fichiers;
    }

    public function addFichier(Fichier $fichier): static
    {
        if (!$this->fichiers->contains($fichier)) {
            $this->fichiers->add($fichier);
            $fichier->setUser($this);
        }

        return $this;
    }

    public function removeFichier(Fichier $fichier): static
    {
        if ($this->fichiers->removeElement($fichier)) {
            // set the owning side to null (unless already changed)
            if ($fichier->getUser() === $this) {
                $fichier->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/UtilisateurController.php
<?php

namespace App\Controller;

use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class UtilisateurController extends AbstractController
{

    #[Route('/mod-liste-utilisateurs', name: 'app_liste_utilisateurs')]
    public function listeUtilisateurs(UserRepository $userRepository): Response
    {
        $users = $userRepository->findAll();
        return $this->render('utilisateur/liste-utilisateurs.html.twig', [
            'users' => $users,
        ]);
    }

    #[Route('/profil', name: 'app_profil')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function profil(): Response
    {

        $user = $this->getUser();

        if (!$user) {
            throw $this->createAccessDeniedException('Vous devez être connecté pour accéder à cette page.');
        }
        return $this->render('utilisateur/profil.html.twig', [
            'user' => $user,
        ]);
    }

}

templates/utilisateur/liste-utilisateurs.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    {{ parent() }}Liste des utilisateurs
{% endblock %}
{% block body %}
    <div class="container-fluid">
        <h1 class="text-center text-primary mt-4 pt-4 display-1 fw-bold">Liste des utilisateurs</h1>
        <div class="row justify-content-center">
            <div class="col-12 col-md-8 bg-white p-4 m-0 text-primary">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr class="fw-bold text-primary">
                                <th scope="col">Email</th>
                                <th scope="col">Date d'inscription</th>
                                <th scope="col">Rôle</th>
                                <th scope="col">Nombre de fichiers</th> <!-- Nouvelle colonne -->
                            </tr>
                        </thead>
                        <tbody>
                            {% for user in users | sort((a, b) => b.id <=> a.id) %}
                                <tr class="{{ cycle(['table-primary', 'table-secondary'], loop.index0) }}">
                                    <td>{{ user.email | capitalize }}</td>
                                    <td>{{ user.dateInscription | date("d-m-Y à H:i:s") }}</td>
                                    <td>
                                        {% if 'ROLE_ADMIN' in user.roles %}
                                            Administrateur
                                        {% elseif 'ROLE_MODERATOR' in user.roles %}
                                            Modérateur
                                        {% else %}
                                            Utilisateur
                                        {% endif %}
                                    </td>
                                    <td>{{ user.fichiers | length }}</td> <!-- Affichage du nombre de fichiers -->
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/utilisateur/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Profil - {{ parent() }}
{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1 class="text-center text-primary">Profil</h1>
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 border rounded">
                <ul class="list-unstyled">
                    <li><strong>Email :</strong> {{ user.email |capitalize  }}</li>
                    <li><strong>Nom :</strong> {{ user.nom |capitalize  }}</li>
                    <li><strong>P :</strong> {{ user.prenom |capitalize  }}</li>
                    <li><strong>Date d'inscription :</strong> {{ user.dateInscription | date('d-m-Y') }}</li>
                    <li><strong>Rôle :</strong> 
                        {% if 'ROLE_ADMIN' in user.roles %}
                            Administrateur
                        {% elseif 'ROLE_MOD' in user.roles %}
                            Modérateur
                        {% else %}
                            Utilisateur
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}